services:
  svitlolocator:
    build:
      context: .
      dockerfile: Dockerfile
    image: svitlolocator:latest
    container_name: svitlolocator
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - traefik-public
      - internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      
      - "traefik.http.routers.svitlolocator.rule=Host(`svitlo-finder.xyz`) || Host(`www.svitlo-finder.xyz`)"
      - "traefik.http.routers.svitlolocator.entrypoints=websecure"
      - "traefik.http.routers.svitlolocator.tls=true"
      - "traefik.http.routers.svitlolocator.tls.certresolver=myresolver"

      - "traefik.http.services.svitlolocator.loadbalancer.server.port=8082"

  redis:
    image: redis:alpine
    container_name: svitlolocator_redis
    restart: unless-stopped
    networks:
      - internal-net

  overpass:
    image: wiktorn/overpass-api:latest
    container_name: local_overpass
    ports:
      - "12345:80"
    volumes:
      - overpass-db:/db
    healthcheck:
      disable: true
    environment:
      - OVERPASS_MODE=init
      # Стабільне посилання на OSM екстракт Києва (BBBike)
      - OVERPASS_PLANET_URL=https://download.bbbike.org/osm/bbbike/Kiew/Kiew.osm.pbf
      # Препроцесинг для конвертації PBF у формат OSM BZ2 за допомогою osmium
      - OVERPASS_PLANET_PREPROCESS=mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf && chown -R overpass:overpass /db
      # Вимикаємо оновлення метаданих
      - OVERPASS_META=no
    restart: always
    networks:
      - traefik-public
      - internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.overpass.rule=(Host(`svitlo-finder.xyz`) || Host(`www.svitlo-finder.xyz`)) && PathPrefix(`/overpass`)"
      - "traefik.http.routers.overpass.priority=100"
      - "traefik.http.routers.overpass.entrypoints=websecure"
      - "traefik.http.routers.overpass.tls=true"
      - "traefik.http.routers.overpass.tls.certresolver=myresolver"
      - "traefik.http.middlewares.overpass-stripprefix.stripprefix.prefixes=/overpass"
      - "traefik.http.routers.overpass.middlewares=overpass-stripprefix"
      - "traefik.http.services.overpass.loadbalancer.server.port=80"

volumes:
  overpass-db:

networks:
  traefik-public:
    external: true
  internal-net: