services:
  svitlolocator:
    build:
      context: .
      dockerfile: Dockerfile
    image: svitlolocator:latest
    container_name: svitlolocator
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - traefik-public
      - internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      
      - "traefik.http.routers.svitlolocator.rule=Host(`svitlo-finder.xyz`) || Host(`www.svitlo-finder.xyz`)"
      - "traefik.http.routers.svitlolocator.entrypoints=websecure"
      - "traefik.http.routers.svitlolocator.tls=true"
      - "traefik.http.routers.svitlolocator.tls.certresolver=myresolver"

      - "traefik.http.services.svitlolocator.loadbalancer.server.port=8082"

  redis:
    image: redis:alpine
    container_name: svitlolocator_redis
    restart: unless-stopped
    networks:
      - internal-net

  loki:
    image: grafana/loki:2.9.0
    container_name: svitlolocator_loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.0
    container_name: svitlolocator_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
      - promtail-data:/run/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: svitlolocator_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

networks:
  traefik-public:
    external: true
  internal-net:
  monitoring:
    name: monitoring

volumes:
  loki-data:
  promtail-data:
  grafana-data: